# Generated by Django 6.0.3 on 2026-03-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="price",
            field=models.FloatField(),
        ),
    ]
